API-28194 codeql missing csrf
department-of-veterans-affairs/lighthouse-saml-proxy pull request #454
Opened 2023-07-18 18:32 UTC by dmekala-va

This PR addresses this codeql alert scan:
https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/security/code-scanning/8

Link to Jira: https://jira.devops.va.gov/browse/API-28194

2023-07-18 21:53 UTC, johnmweisz commented on src/routes/index.js
> +  app.use(
I think there should only be one app.use
consider doing as described below from the documentation:
app.use(lusca({
    csrf: true,
    csp: { /* ... */},
    xframe: 'SAMEORIGIN',
    p3p: 'ABCDEF',
    hsts: {maxAge: 31536000, includeSubDomains: true, preload: true},
    xssProtection: true,
    nosniff: true,
    referrerPolicy: 'same-origin'
}));

2023-07-19 00:02 UTC, dbrown-va commented on src/routes/index.js
> +import lusca from "lusca";
Confirmed we are using `express-session` which is called out as a requirement in the lusca docs.

2023-07-19 00:04 UTC, dbrown-va commented on src/routes/index.js
> +      csrf: false,
I would have expected `csrf` protection to have been enabled here.  But perhaps I am misunderstanding the lusca docs.

2023-07-19 00:05 UTC, dbrown-va commented on src/routes/index.js
> +  app.use(lusca.xframe("SAMEORIGIN"));
The various lusca docs should be consolidated to a single entry w/ config, similar to the session configuration above.

```
app.use(lusca({
    csrf: true,
    xframe: 'SAMEORIGIN',
    p3p: 'ABCDEF',
    hsts: {maxAge: 31536000},
    xssProtection: true,
}));
```

2023-07-19 00:06 UTC, dbrown-va requested changes
Would like to see the `app.use` statements consolidated to a single statement with config as noted in the reviewer.

2023-07-19 00:56 UTC, dmekala-va commented on src/routes/index.js
> +      csrf: false,
after trial and error I found that csrf being set to false is the only fix that works. I did try setting to true but it was failing the csrf fix and saml-proxy happy path. It wasn't finding the csrf token

2023-07-19 16:43 UTC, johnmweisz commented on src/routes/index.js
> +      csrf: false,
If this does rely on session, I would expect it to be unstable as we are using the in memory local development version of session which is not shared across tasks.  We also do a lot of redirecting to other sites, which would also impact the stability.

2023-07-19 16:49 UTC, johnmweisz commented on src/routes/index.js
> +      csrf: false,
Again, I'm concerned about this being necessary and stable.

2023-07-21 19:25 UTC, crolarlibertyva commented on src/routes/index.js
> +      csrf: false,
Bullet bitten. Confirmed the sessions are winding up in the redis cache.

2023-07-24 20:41 UTC, johnmweisz commented on src/routes/index.js
> +      csrf: false,
removing session is probably better than using redis

2023-07-24 21:16 UTC, dmekala-va commented on src/routes/index.js
> +      csrf: false,
reverted redis change. was failing build

2023-07-28 13:44 UTC, closed without merging

2023-07-29 23:09 UTC, crolarlibertyva commented
Heads up. Working the session aspect in a different branch.https://github.com/department-of-veterans-affairs/lighthouse-saml-proxy/tree/API-28194-redis-session.